### ISSUE TITLE
DockerBuild - arm64

### ISSUE THREAD

**Issue by sincze** [hvxl/otmonitor#25]
Hi 

I noticed the offering of otmonitor running in a docker.
Current docker seems not compatible with arm64/arm7/arm8. 

Any chance to share the Dockerbuild (https://github.com/hvxl/otmonitor/blob/master/Dockerfile) or offer an additional docker image compatible with ARM ?

Kind Regards.

**Comment by algol-ch** [comment]
Hi

I am successfully running otmonitor in docker on my RPi4 (arm64v8) using the following dockerfile:

```
# Use an ARM compatible base image
FROM arm64v8/debian:latest

# Set the working directory inside the container
WORKDIR /usr/src/app

# Install missing library
ARG DEBIAN_FRONTEND=non interactive
RUN apt-get update
RUN apt-get -qq install libxft2

# Copy the binary file from docker build directory into the container
COPY otmonitor ./

# Make sure the file is executable
RUN chmod +x otmonitor

# Set the binary as the entrypoint
ENTRYPOINT ["./otmonitor", "--daemon", "-f", "/data/otmonitor.conf"]

```
Note that I have chosen to remain at version 5.1 of otmonitor (since 5.2, changes to the CS command validity unfortunately break how I manage my boiler).

Hope this helps!

**Comment by sincze** [comment]
Many Thanks for sharing @algol-ch 
Now have a working setup with:

```
# Use an ARM64-compatible base image
FROM arm64v8/debian:latest

# Set the maintainer label
LABEL maintainer="Schelte Bron <otgw@tclcode.com>"

# Set the working directory inside the container
WORKDIR /usr/src/app

# Install necessary dependencies
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    libxft2 \
    curl \
    ca-certificates \
    tzdata && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Create necessary directories with proper permissions
RUN mkdir -p /usr/local/bin && mkdir -p -m a=rwx /data /log

# Download the latest ARM64 otmonitor binary with error handling
RUN curl -fsSL -o /usr/local/bin/otmonitor https://otgw.tclcode.com/download/otmonitor-aarch64 && \
    chmod +x /usr/local/bin/otmonitor || \
    { echo "Failed to download otmonitor binary"; exit 1; }

# Expose the port used by otmonitor
EXPOSE 8080

# Set otmonitor as the entrypoint with default arguments
ENTRYPOINT ["/usr/local/bin/otmonitor", "--daemon", "-f/data/otmonitor.conf"]
CMD ["-w8080"]

# Set the log directory as the working directory
WORKDIR /log

```

Build a container:
`sudo docker build . < Dockerfile -t sincze/otmonitor:arm64
`
and the following in the docker-compose.

```
version: '3.0'

services:
  otmonitor:
    container_name: otmonitor
    hostname: otmonitor
##    image: hvxl/otmonitor:stable
    image: sincze/otmonitor:arm64
    ports:
      - "2380:8080"
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ./otmonitor/.config/otmonitor:/data
      - ./otmonitor/otlogs:/log
    user: "${UID}:${GID}"
    restart: unless-stopped
    networks:
      proxy:

```
